version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: vga_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "3007"
      POSTGRES_DB: vga_store
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql
      - ./database/seed_vga.sql:/docker-entrypoint-initdb.d/2-seed_vga.sql

  backend:
    build:
      context: ./backend/vgashop
      dockerfile: Dockerfile
    container_name: vga_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vga_store?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=3007
    volumes:
      - vga_uploads:/app/uploads
    depends_on:
      - db

  admin-frontend:
    build:
      context: ./fontend/admin
      dockerfile: Dockerfile
    container_name: vga_admin
    ports:
      - "5174:80"
    depends_on:
      - backend

  user-frontend:
    build:
      context: ./fontend/user
      dockerfile: Dockerfile
    container_name: vga_user
    ports:
      - "5173:80"
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    container_name: vga_jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
  vga_uploads:
  jenkins_home:
